### PR TITLE
Support Safari 9.

### PR DESCRIPTION
**Pull request by simonness**
In Safari 9 and below the following script error occurs:

`SyntaxError unexpected keyword 'const'. const declarations are not supported in strict mode`

I notice that Safari 9 is a supported browser in the SDK package [documentation ]((https://firebase.google.com/support/guides/environments_js-sdk#suggested-polyfills) and have seen other issues and fixes such as https://github.com/firebase/firebase-js-sdk/issues/931 to get the SDK working on Safari 9.  

Whilst it works, I'm just not sure this is the best fix for getting the UI package working on Safari 9, so happy to see any alternative approaches :)

### CODE REVIEW

**Comment by simonness** [comment]
@googlebot I signed it!

**Comment by bojeil-google** [comment]
I am not sure this is the right approach. You are proposing changes to the ES6 module. I think you should use some bundler like webpack to convert to ES5.
If you are using the CDN version, it should be in ES5 format already.

**Comment by simonness** [comment]
Thanks @bojeil-google happy to go with either of those solutions.

**Comment by Rob-ot** [comment]
Let me argue for this change a bit.

As you may know, typically web browser modules published to npm are strictly ES5, where any ES6+ files are transpiled on publish. This is what firebase-ui does too already, the 3 JS files in the `dist` folder are all ES5 (from what I can tell) with one exception -- the last line in `esm.js` is `const auth = firebaseui.auth;export { auth } ;`. That final piece is concatenated to the end of the file during the gulp build, which happens _after_ the file has been transpiled to ES5.

So, this single `const` makes the file ES5-invalid.

Additionally, a couple lines down from this change in the gulpfile, `var` is used instead of const/let, so I believe it was intended for these concatenated bits to be ES5. https://github.com/firebase/firebaseui-web/blob/master/gulpfile.js#L86

Please reconsider this PR and make this modules ES5-compatible as I believe was originally intended. Thanks!

**Comment by Rob-ot** [comment]
> Please reconsider this PR and make this modules ES5-compatible as I believe was originally intended. Thanks!

@bojeil-google any thoughts on this re: #769?

**Comment by bojeil-google** [comment]
Ok, to simplify things, think it would be safe to merge this. Will merge once tests pass.
Thanks again for the fix.

**Comment by simonness** [comment]
Thanks @Rob-ot, @bojeil-google :)

**Review by bojeil-google — APPROVED** [review]

**Pull request merged**
