### PR TITLE
WIP firebaseui-web vNext

### PR DESCRIPTION
**Pull request by jamesdaniels**
Just a WIP of a possible rewrite for vNext using web components (Stencil.js) more info coming soon.

[Demo](https://fir-ui-test-7cd1d.web.app/)

### CODE REVIEW

**Comment by bojeil-google** [comment]
Hey @jamesdaniels I am not aware of the context behind this project. Please set up a meeting with me so we can discuss before we can proceed.

**Comment by jamesdaniels** [comment]
> Hey @jamesdaniels I am not aware of the context behind this project. Please set up a meeting with me so we can discuss before we can proceed.

Will do. @davideast and I have been experimenting and we will share more of our thoughts, results, and plans shortly. 

Also don't mind the state of this PR and the "bull dozing", I had been developing in a clean repo and just bringing it over here for visibility.

**Comment by bojeil-google** [comment]
> > Hey @jamesdaniels I am not aware of the context behind this project. Please set up a meeting with me so we can discuss before we can proceed.
> 
> Will do. @davideast and I have been experimenting and we will share more of our thoughts, results, and plans shortly.
> 
> Also don't mind the state of this PR and the "bull dozing", I had been developing in a clean repo and just bringing it over here (as a WIP) for visibility.

Sounds good. Thanks.

**Comment by jamesdaniels** [comment]
Closing as we'll be doing this work elsewhere.

**Pull request closed without merging**
