### PR TITLE
Support multi factor authentication

### LINKED ISSUE #782: Support for Multi-Factor Auth?
Hello,

I just wired up Multi-Factor authentication for my password auth, and it works great.  But when I try to log in via Google Auth through FirebaseUI, I get the following popup message:

Screen Shot 2020-11-15 at 3 23 47 PM

says "Proof of ownership of a second factor is required to complete sign-in."

The callbacks `signInFailure` and `signInSuccessWithAuthResult` are not called, so I can't handle this error and redirect to my confirmation code form.

Also, I can't find any examples online on how to use MFA with FirebaseUI.

Question 1: Does Firebase UI support MFA?
Question 2: If so, is there a canonical example on how to make it work?
Question 3: If Question #1 is a no, will it be or can it please be supported?

### LINKED ISSUE #843: Add support for MFA UI
Cloud Identity Platform supports MFA, but the firebase UI seems to doesn't support this and requires developing a custom UI. It would be very helpful if this could be included out of the box.

### PR DESCRIPTION
**Pull request by nguyenduyhust**
Support multi factor authentication

Fix #782
Fix #843

https://user-images.githubusercontent.com/19814612/155684047-f6f7668e-a4f2-4520-9be5-260ed7ac57ad.mp4

### CODE REVIEW

**Comment by lordlele** [comment]
@nguyenduyhust any news on this? Why is not already merged on the master branch?

**Comment by nguyenduyhust** [comment]
@lordlele This PR only work with firebase v8. There are some different with firebase v9. So I close it.

**Comment by nguyenduyhust** [comment]
@lordlele I have forked and modified to support MFA in https://github.com/gulabs/firebaseui-web. You can try it.

**Comment by lordlele** [comment]
> @lordlele I have forked and modified to support MFA in https://github.com/gulabs/firebaseui-web. You can try it.

I'll give a try right now!

**Comment by amit-bs23** [comment]
@nguyenduyhust How to add this https://github.com/gulabs/firebaseui-web as an npm dependency?

**Comment by nguyenduyhust** [comment]
> @nguyenduyhust How to add this https://github.com/gulabs/firebaseui-web as an npm dependency?

For now, we haven't push it to npm. But you can install directly from github by `npm install github:gulabs/firebaseui-web#v5.0.8`

**Comment by meena-erian** [comment]
Hi @nguyenduyhust  I love what you did here! Any idea if it's ever going to be merged? 


I tried
```
npm install github:gulabs/firebaseui-web#v5.0.8
``` 
but it doesn't seem to work as it doesn't go through all the build steps of the project before adding it to the node_modules folder

And the master branch is ahead by 30 commits now :(

**Comment by bayareacoder** [comment]
@nguyenduyhust I npm installed this library. How do I run your example code that shows the 2FA as in the video you posted? I tried to run what is in the demo folder but that logs in without 2FA, although I have 2FA set on my firebase auth settings. Does something else need to be done? If so, pls outline all steps clearly. (it's not clear because the README is not changed from the forked project)

**Pull request closed without merging**
