### PR TITLE
Fix SignInOption type

### PR DESCRIPTION
**Pull request by shiatsumat**
Fix SignInOption type.

### CODE REVIEW

**Comment by shiatsumat** [comment]
Typescript doesn't allow extra fields in the usual use.
https://github.com/Microsoft/TypeScript/issues/6963

We can possibly set `signInOptions?: Array<string | FederatedSignInOption | EmailSignInOption | PhoneSignInOption >;`;
but since [firebaseui-externs.js](https://github.com/firebase/firebaseui-web/blob/master/externs/firebaseui-externs.js) simply defines `SignInOption` interface equipped with authMethod, requireDisplayName, recaptchaParameters etc., I decided to make [index.d.ts](https://github.com/firebase/firebaseui-web/blob/master/types/index.d.ts) agree with the interface definition.

**Comment by bojeil-google** [comment]
Putting all the fields in one interface is a bad idea and defeats the purpose of types. You can mix fields from different SignInOptions without any way of validating them.

**Comment by shiatsumat** [comment]
OK, I'll make another PR with richer types.

**Comment by shiatsumat** [comment]
I made this PR. https://github.com/firebase/firebaseui-web/pull/470

**Pull request closed without merging**
