### PR TITLE
Remove dependencies from ES module

### LINKED ISSUE #618: When bundled with Parcel, require returns dialog-polyfill instead
### Describe your environment

* Operating System version: Windows 10
* Browser version: Firefox 68.0.1
* Firebase UI version: 4.1.0
* Firebase SDK version: 6.3.5

### Describe the problem

When bundled with [Parcel](https://parceljs.org/), trying `firebaseui` imports resolve to `dialog-polyfill` instead.

#### Steps to reproduce:

Just try installing and requiring it. Minimal repro here: https://github.com/fongandrew/parcel-firebaseui

It's likely this is an issue with Parcel since I'm unable to repro this issue with Webpack or plain Node, and I'll open an issue over there too. But I'm reporting here too since `firebaseui` in case it's something it ends up being something that could be resolved with a small tweak to the Gulp build or something.

### PR DESCRIPTION
**Pull request by LuudJanssen**
Fixes #618 

Instead of bundling the dependencies for the ES module, let's import them. This fixes the issue of `dialog-polyfill` also defining an export and bundlers getting confused.

I tried to run the tests, but ran into issues with PhantomJS, so if anyone from the team could run the tests, that would be nice.

### CODE REVIEW

**Comment by LuudJanssen** [comment]
@googlebot I signed it!

**Comment by LuudJanssen** [comment]
@wti806 Of course, that's why the plain script version and CJS version will still have all dependencies included. The concatWithDeps function now accepts a list of dependencies. On the plain script version and CJS version the dependencies get injected, only the ES module version bundles no dependencies.

Or am I missing something here?

**Comment by wti806** [comment]
You are right. The change looks good. Did you test with all the 3 versions? I think we need to be very carefully with change like this. I'll also need to clone your branch and test before we can merge the change. Thanks again for your contribution!

**Comment by LuudJanssen** [comment]
Hey @wti806, sorry it took me a while to get back to you.

Because I moved the order of the CJS packages to be consistent with the ESM dependencies (so first dialog-polyfill and then the material-design-lite dependencies), all output files will change. However, I [created a branch](https://github.com/LuudJanssen/firebaseui-web/compare/master...LuudJanssen:feature/move-dialog-polyfill-import) in which I temporarily switched the order to match the original. When checking the output of the CommonJS files now, they are exactly the same, only the `esm__en.js` and `esm.js` file change:

_Output of `diff -rq dist-old/ dist-new`:_
```
Files dist-old/esm__en.js and dist-new/esm__en.js differ
Files dist-old/esm.js and dist-new/esm.js differ
```

So I'm confident my changes won't affect anyone using the CJS imports. I've tested my changes using Parcel (which had the problem in the first place) and it works now, and as there are no other exports in the resulting `esm.js` file I'm confident other bundlers like Webpack and Rollup will also continue to work.

However, I suggest you test it for yourself and see how my changes affect the output and the risks associated with it.

**Comment by wti806** [comment]
@LuudJanssen Sure. I'll test again on my end. You can sync your branch from master cause the integration test are failing and we fixed it in master branch. Once the test passes, I'll approve the change.

**Comment by LuudJanssen** [comment]
@wti806 I updated my master branch!

**Pull request merged**
