### PR TITLE
Update README.md -  isPendingRedirect

### PR DESCRIPTION
**Pull request by RaphaelJenni**
Fixed isPendingRedirect documentation

### CODE REVIEW

**Comment by RaphaelJenni** [comment]
I signed it!

**Comment by bojeil-google** [comment]
Hey @RaphaelJenni, this change is incorrect. You are not using this API correctly.
This API is only relevant for single page apps or apps where the sign-in UI is rendered conditionally (if a user clicks a button on the page to sign-in/up, etc). When the user returns back to the page from an OAuth redirect, you need to check if there is a pending sign-in with redirect operation. If so, you would render the UI to complete that. You are welcome to update the PR with this. Otherwise, I can do it.

**Comment by RaphaelJenni** [comment]
I can do it.

**Comment by RaphaelJenni** [comment]
It actually makes much more sense to me now. I tried to update the documentation. Hopefully in the correct way.

**Comment by bojeil-google** [comment]
Please re-sync to master so your branch is up to date before we can merge.

**Pull request merged**
