### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these [code quality badges](https://lgtm.com/projects/g/firebase/firebaseui-web/ci/#badges) to your project. They will indicate a very high code quality to potential users and contributors.
To get an idea of the analyses reflected by these grades, check the alerts discovered by [LGTM](https://lgtm.com/projects/g/firebase/firebaseui-web).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by xcorail** [comment]
I signed it!

**Comment by bojeil-google** [comment]
Thanks @xcorail, but we try to minimize the number of third-party badges on our Firebase projects.

**Comment by xcorail** [comment]
Hi @bojeil-google 

I totally understand this. Thanks for taking the time to answer me.

The [LGTM alerts](https://lgtm.com/projects/g/firebase/firebaseui-web/alerts/?mode=tree) will however always be there for you at any time.

**Comment by bojeil-google** [comment]
Thanks. We will keep that in mind.

**Pull request closed without merging**
