### PR TITLE
Write about privacy policy URL to README

### PR DESCRIPTION
**Pull request by deraru**
Hello,

I started to integrate firebase authentication to our app with this package.
Then I found the lack of the config about `privacyPolicyUrl` in README.
This pull request adds it to README. 😄

### CODE REVIEW

**Comment by deraru** [comment]
I signed it!

**Comment by bojeil-google** [comment]
Our integration tests seem to be broken for some reason. We are looking into that.

**Comment by wti806** [comment]
@deraru  Instead of creating PR from your own fork, could you please clone the repo directly and create a PR from there? I don't know why but it seems there is some problem running the Travis CI test if the PR is from your own fork. Or if you prefer to let me make the change, I can also update the sample code. Thanks for contributing to the repo!

**Comment by deraru** [comment]
Thank you for replying.
I will create a pull request from the cloned repo.

**Comment by wti806** [comment]
@deraru I've already updated the doc in PR#[458](https://github.com/firebase/firebaseui-web/pull/458)  as part of release V3.2. Thanks again for pointing it out.

**Pull request closed without merging**
