### PR TITLE
Use new CDN location.

### PR DESCRIPTION
**Pull request by danieljy**
The old one no longer works.

### CODE REVIEW

**Comment by danieljy** [comment]
I signed it.

**Comment by bojeil-google** [comment]
Is `https://cdn.firebase.com/libs/firebaseui/2.5.1/firebaseui.js` not working for you? I just checked the firebase cdn ones and they seem fine.

**Comment by danieljy** [comment]
Interesting. It must have been a temporary failure.

I was getting SSL errors locally, and then ran this test:


https://www.sslshopper.com/ssl-checker.html#hostname=https://cdn.firebase.com

This test confirmed that the certificate did not have cdn.firebase.com
associated with it.

I guess you can keep it as is then, though the URLs I suggest are much more
aligned with the ones that are suggested for i18n, so it may still be a
good idea to keep them aligned.

Is there a drawback to using these (just for my information, since we just
changed all of our urls to it)?

**Comment by bojeil-google** [comment]
Both links work for now. We have no short term plans to remove either. The difference is that the `cdn.firebase.com` version is built using open source compiler where as the `gstatic` one is not.

**Comment by danieljy** [comment]
Thanks for your quick replies and explanations!

**Pull request closed without merging**
